# .github/workflows/module-ci.yml
name: Terraform CI

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Format Check
        run: terraform fmt -check -recursive

      - name: Validate
        run: |
          cd examples/complete
          terraform init -backend=false
          terraform validate
